{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.7.aar",
          "url": "acttrader-charts-android-1.3.0-beta.7.aar",
          "size": 424479,
          "sha512": "2f72ccc59c1628bd8d5e5a8e36758d0494802ef367e613e5538a8d6acb1e06258f9c035bb4ec1c0a14fe6c420b980bcf01a6a28dde74c688063c79af4676a969",
          "sha256": "eea871b7199bf16364b3b2f9232d27226ea0f170832e1d5b35e2f0e2a2ec967f",
          "sha1": "906dbd05414c30e5b9245d6c145e4af0d5f57296",
          "md5": "9a2fc10293c23f0508fc87381fbc198d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.7.aar",
          "url": "acttrader-charts-android-1.3.0-beta.7.aar",
          "size": 424479,
          "sha512": "2f72ccc59c1628bd8d5e5a8e36758d0494802ef367e613e5538a8d6acb1e06258f9c035bb4ec1c0a14fe6c420b980bcf01a6a28dde74c688063c79af4676a969",
          "sha256": "eea871b7199bf16364b3b2f9232d27226ea0f170832e1d5b35e2f0e2a2ec967f",
          "sha1": "906dbd05414c30e5b9245d6c145e4af0d5f57296",
          "md5": "9a2fc10293c23f0508fc87381fbc198d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.7-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.7-sources.jar",
          "size": 31628,
          "sha512": "1baad867199366fa746d5ee1dd85d5d701d7678ebc987575fcb5c896ad805c6d1d06d45768821ca4a59f8d0085c33e6a3579cc2501aab17752132123d9605add",
          "sha256": "8df4e30597f38930cf6f9c81f706ee1853e280f2bf503f4c7fc3e9f2af22ab8d",
          "sha1": "51c0f966eb0ff051487c3c745b6fac1ad950ff9d",
          "md5": "d871882c90f739fe72b9a6d62de49907"
        }
      ]
    }
  ]
}
