{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.31.aar",
          "url": "acttrader-charts-android-1.3.0-beta.31.aar",
          "size": 692222,
          "sha512": "a3353b10e37c9542ec13883a357b1a68fd697d77f08cae7630842eff48c00de9a1ef3edd04b2c2f8b980573c8eb95fa216c150c534e61acb6bda787b3a36f0ee",
          "sha256": "67bc1ba34fc2ebfe60a3f2ddd7a016b9fcfeb82935852af205c57799fc73b321",
          "sha1": "ac0654a7c91538a24afce42b528fa2789151983e",
          "md5": "3f030282c09deeec2ebac66535610220"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.31.aar",
          "url": "acttrader-charts-android-1.3.0-beta.31.aar",
          "size": 692222,
          "sha512": "a3353b10e37c9542ec13883a357b1a68fd697d77f08cae7630842eff48c00de9a1ef3edd04b2c2f8b980573c8eb95fa216c150c534e61acb6bda787b3a36f0ee",
          "sha256": "67bc1ba34fc2ebfe60a3f2ddd7a016b9fcfeb82935852af205c57799fc73b321",
          "sha1": "ac0654a7c91538a24afce42b528fa2789151983e",
          "md5": "3f030282c09deeec2ebac66535610220"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.31-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.31-sources.jar",
          "size": 51443,
          "sha512": "e1636ee04cf0a3374a35f84d4bc482dcbeeb0f9994adb5d0fcb1555513f0a781a71bdf4dd3eb3fa84b641cde37f60f1f6f535aa9e66a14e2e14db759c257abcf",
          "sha256": "3406993dcce9c9743212c5ed5d3ba6021f2204606a675fb98385e9ff71362e37",
          "sha1": "1cd64161614f81c43f5ed2e5fe14925d771759c1",
          "md5": "efbd7339c688fc895f3e5a2e3e782e6e"
        }
      ]
    }
  ]
}
