{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.11.aar",
          "url": "acttrader-charts-android-1.3.0-beta.11.aar",
          "size": 445583,
          "sha512": "44b6d50d0625dc0be4496f1eec986bbccb76341c82f341101e6a25d3d3d4eff33b665635b2000a380974b6472391101b30c38cc1b56620d0e778ef65e74c2ca6",
          "sha256": "c983998e5463c4b5b2688640e3de395a866a27c5f67408b9fa545ddb19d3384e",
          "sha1": "086903d76d2410eb0c2ddda7808c6b30d50ac889",
          "md5": "f6d50cc0556357f702a50440525751c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.11.aar",
          "url": "acttrader-charts-android-1.3.0-beta.11.aar",
          "size": 445583,
          "sha512": "44b6d50d0625dc0be4496f1eec986bbccb76341c82f341101e6a25d3d3d4eff33b665635b2000a380974b6472391101b30c38cc1b56620d0e778ef65e74c2ca6",
          "sha256": "c983998e5463c4b5b2688640e3de395a866a27c5f67408b9fa545ddb19d3384e",
          "sha1": "086903d76d2410eb0c2ddda7808c6b30d50ac889",
          "md5": "f6d50cc0556357f702a50440525751c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.11-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.11-sources.jar",
          "size": 35445,
          "sha512": "3cf7d20010ebecbed6494b4162a97073c55b4ac18952ef3856354b6dac773496f1f7f3cd9034b4f4196b327b66104b498aa95953c0bf6183df2d8867c3cd2839",
          "sha256": "7472cb7671266fa244bf6269c2ef99d764168a40bd7aedd7fad532da716c282e",
          "sha1": "bc0f1f752dd598d5d7d8f2bcdb447af6a79338b2",
          "md5": "1e8c2c6c88b34620fee6fbb6e6a43866"
        }
      ]
    }
  ]
}
