{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.14.aar",
          "url": "acttrader-charts-android-1.3.0-beta.14.aar",
          "size": 445741,
          "sha512": "d485800ab3dd0995ec076f1e3f9e958ddb895a7217cb814e6af420a5932f1bf1e5d337a963ee81c82ba179ced7931b2ce53fd8916ba1f5b73608396627f23f9a",
          "sha256": "751a8f177fa9e6d11a6e6de212693efcb8050cb817677754fb435b441c23d09a",
          "sha1": "7cb317d22313ed7c0e771213cca42728e12db38c",
          "md5": "55ca48979bc49735a8eb634df4384557"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.14.aar",
          "url": "acttrader-charts-android-1.3.0-beta.14.aar",
          "size": 445741,
          "sha512": "d485800ab3dd0995ec076f1e3f9e958ddb895a7217cb814e6af420a5932f1bf1e5d337a963ee81c82ba179ced7931b2ce53fd8916ba1f5b73608396627f23f9a",
          "sha256": "751a8f177fa9e6d11a6e6de212693efcb8050cb817677754fb435b441c23d09a",
          "sha1": "7cb317d22313ed7c0e771213cca42728e12db38c",
          "md5": "55ca48979bc49735a8eb634df4384557"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.14-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.14-sources.jar",
          "size": 35445,
          "sha512": "3cf7d20010ebecbed6494b4162a97073c55b4ac18952ef3856354b6dac773496f1f7f3cd9034b4f4196b327b66104b498aa95953c0bf6183df2d8867c3cd2839",
          "sha256": "7472cb7671266fa244bf6269c2ef99d764168a40bd7aedd7fad532da716c282e",
          "sha1": "bc0f1f752dd598d5d7d8f2bcdb447af6a79338b2",
          "md5": "1e8c2c6c88b34620fee6fbb6e6a43866"
        }
      ]
    }
  ]
}
