{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.25.aar",
          "url": "acttrader-charts-android-1.3.0-beta.25.aar",
          "size": 477535,
          "sha512": "d76bfaa3c57d8e75398a1a6cd44cbf0566cf25ee09a61be9abad0ff69f47ef63664fac9813e398a07ee186f4be2d33c89d1d0547ca8c2df9bfa2c09218649538",
          "sha256": "cef238ab4401f6276abbe89d4cf6a810e94a4e39828c7d80e7955b962ab318f8",
          "sha1": "37a3e5750f90a5c4de411bb43bd5a660a4cac535",
          "md5": "74e2d91fe8a8b6a2c4697c390637fb71"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.25.aar",
          "url": "acttrader-charts-android-1.3.0-beta.25.aar",
          "size": 477535,
          "sha512": "d76bfaa3c57d8e75398a1a6cd44cbf0566cf25ee09a61be9abad0ff69f47ef63664fac9813e398a07ee186f4be2d33c89d1d0547ca8c2df9bfa2c09218649538",
          "sha256": "cef238ab4401f6276abbe89d4cf6a810e94a4e39828c7d80e7955b962ab318f8",
          "sha1": "37a3e5750f90a5c4de411bb43bd5a660a4cac535",
          "md5": "74e2d91fe8a8b6a2c4697c390637fb71"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.25-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.25-sources.jar",
          "size": 38877,
          "sha512": "00f7e853d5fd31dc33150220edcdd537a23aaeb1233039cdfdc8ed63a961f13ce8725388667ac5ef048f5b8d072b672a82249006c20228ad40bb5effe39898b1",
          "sha256": "68268391a7169f64e8920af5f6de16ef1b579c38809f01b3f91ba77d2260de58",
          "sha1": "23c4d30b7a06f220a894f3638262fa203a007d26",
          "md5": "1f60537a1f6aa56a98b22bd7c949858f"
        }
      ]
    }
  ]
}
