{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.28.aar",
          "url": "acttrader-charts-android-1.3.0-beta.28.aar",
          "size": 665665,
          "sha512": "0c7cd31577d7b48df99387b0f5bfb3fb8771fbc5f4486791570548aec4925dc3b23565a875bdbe39f129d27574657488b17d5839491f25ea5700a289d7218b98",
          "sha256": "92c6115f57ced55fb7e4aba902e8845804e0981f28543eb4f27959d1321bf878",
          "sha1": "46b3297236bb4b6aa49e5e70d04e313ae011db35",
          "md5": "c0761668e3827db187d30068dc6e2d30"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.28.aar",
          "url": "acttrader-charts-android-1.3.0-beta.28.aar",
          "size": 665665,
          "sha512": "0c7cd31577d7b48df99387b0f5bfb3fb8771fbc5f4486791570548aec4925dc3b23565a875bdbe39f129d27574657488b17d5839491f25ea5700a289d7218b98",
          "sha256": "92c6115f57ced55fb7e4aba902e8845804e0981f28543eb4f27959d1321bf878",
          "sha1": "46b3297236bb4b6aa49e5e70d04e313ae011db35",
          "md5": "c0761668e3827db187d30068dc6e2d30"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.28-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.28-sources.jar",
          "size": 50160,
          "sha512": "b281c8a3b04b5234ee222761125b2fc8c3f1283317de2aaab87ac79bc3d7685717d4b3b9b128e2b33b35ff7c89400bdcb77bb8efbccda3a2b46abc460441b540",
          "sha256": "2077316428583bd77c52be8b4c79d4605df2e5cd2d782949ddcdc6b550c2a48a",
          "sha1": "094e2cbb2656f3578efc4724909170768601896a",
          "md5": "dace81d6c8cf5a13aa55927a896884f3"
        }
      ]
    }
  ]
}
