{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.18.aar",
          "url": "acttrader-charts-android-1.3.0-beta.18.aar",
          "size": 455522,
          "sha512": "db6e26c2440b64030f22758f708ad8e0f99419dfe4e4b3b276da087ddb988e213826ef1e3d6cba9bb5d4ff05f60d9c042bd52d70a605fd98194832366d6e5a6e",
          "sha256": "6a2cce495c34ce534c9ee007233d63d3dc3728d72e4027f5a795b18e6cf41127",
          "sha1": "691a953357920f14964073456ccda0775f8de780",
          "md5": "2b25ee1fe0f5e0aa24a86d2bbac0d77e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.18.aar",
          "url": "acttrader-charts-android-1.3.0-beta.18.aar",
          "size": 455522,
          "sha512": "db6e26c2440b64030f22758f708ad8e0f99419dfe4e4b3b276da087ddb988e213826ef1e3d6cba9bb5d4ff05f60d9c042bd52d70a605fd98194832366d6e5a6e",
          "sha256": "6a2cce495c34ce534c9ee007233d63d3dc3728d72e4027f5a795b18e6cf41127",
          "sha1": "691a953357920f14964073456ccda0775f8de780",
          "md5": "2b25ee1fe0f5e0aa24a86d2bbac0d77e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.18-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.18-sources.jar",
          "size": 35445,
          "sha512": "3cf7d20010ebecbed6494b4162a97073c55b4ac18952ef3856354b6dac773496f1f7f3cd9034b4f4196b327b66104b498aa95953c0bf6183df2d8867c3cd2839",
          "sha256": "7472cb7671266fa244bf6269c2ef99d764168a40bd7aedd7fad532da716c282e",
          "sha1": "bc0f1f752dd598d5d7d8f2bcdb447af6a79338b2",
          "md5": "1e8c2c6c88b34620fee6fbb6e6a43866"
        }
      ]
    }
  ]
}
