{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.5.aar",
          "url": "acttrader-charts-android-1.3.0-beta.5.aar",
          "size": 418452,
          "sha512": "27e41333799043b479d7b11dd0fecc9f34b4f63b5d85346465d64df982875c2fc2c22292038e9f342eacadd31d0cae99f3766ca8af5012a78131c9fa6faa6f07",
          "sha256": "74b92a3b5e4ae920bfcb8273559da37024c7a2295a2bfa338e92449421fab2dc",
          "sha1": "f21c41523f1b5941130b567d432613c21fadc11f",
          "md5": "40a0d889bf13825d1fdfe57e028ad155"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.5.aar",
          "url": "acttrader-charts-android-1.3.0-beta.5.aar",
          "size": 418452,
          "sha512": "27e41333799043b479d7b11dd0fecc9f34b4f63b5d85346465d64df982875c2fc2c22292038e9f342eacadd31d0cae99f3766ca8af5012a78131c9fa6faa6f07",
          "sha256": "74b92a3b5e4ae920bfcb8273559da37024c7a2295a2bfa338e92449421fab2dc",
          "sha1": "f21c41523f1b5941130b567d432613c21fadc11f",
          "md5": "40a0d889bf13825d1fdfe57e028ad155"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.5-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.5-sources.jar",
          "size": 30971,
          "sha512": "71900e8f2d607b20c00195c7f80747e27297406c23dd51f2991a356a36c837c64fb87096da6c87b984976bd590b992242852db75dc4dc96822700748eea743e2",
          "sha256": "736cbcfd98323a3dcedeb1c7e7713954d043aa98eef4cc809c158470074cfb05",
          "sha1": "1a876469f1ad36fbb2b2636c020790f121acd0bb",
          "md5": "655795cacd3eda69b3efcae34a963a1f"
        }
      ]
    }
  ]
}
