{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.13.aar",
          "url": "acttrader-charts-android-1.3.0-beta.13.aar",
          "size": 445742,
          "sha512": "417de9581d0553d9a23e0c03c4cfe02f57764c26bc81b97c0de713dca7cb244d184b821c806cfdde9991474614500c037e1bd984fb583a2d66a3173aeb1c4e04",
          "sha256": "b0f6ab3ae33745c51347df1ee4a5c14998c03b5219985c2a1bb8246949115fd0",
          "sha1": "a4becc9eb99b7177ca9fb3f56a911d3b13b8b4b9",
          "md5": "0532a641c33218a5c371ccb8a843d543"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.13.aar",
          "url": "acttrader-charts-android-1.3.0-beta.13.aar",
          "size": 445742,
          "sha512": "417de9581d0553d9a23e0c03c4cfe02f57764c26bc81b97c0de713dca7cb244d184b821c806cfdde9991474614500c037e1bd984fb583a2d66a3173aeb1c4e04",
          "sha256": "b0f6ab3ae33745c51347df1ee4a5c14998c03b5219985c2a1bb8246949115fd0",
          "sha1": "a4becc9eb99b7177ca9fb3f56a911d3b13b8b4b9",
          "md5": "0532a641c33218a5c371ccb8a843d543"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.13-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.13-sources.jar",
          "size": 35445,
          "sha512": "3cf7d20010ebecbed6494b4162a97073c55b4ac18952ef3856354b6dac773496f1f7f3cd9034b4f4196b327b66104b498aa95953c0bf6183df2d8867c3cd2839",
          "sha256": "7472cb7671266fa244bf6269c2ef99d764168a40bd7aedd7fad532da716c282e",
          "sha1": "bc0f1f752dd598d5d7d8f2bcdb447af6a79338b2",
          "md5": "1e8c2c6c88b34620fee6fbb6e6a43866"
        }
      ]
    }
  ]
}
