{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.16.aar",
          "url": "acttrader-charts-android-1.3.0-beta.16.aar",
          "size": 446548,
          "sha512": "fb77dc2598e65fb3b9b1b36994803a1a40c77cc5cadf2f81254e10ff1b6a57c55a470ba667ed54a06fbffe01e98721079cf4946983edcb47ba708b18e4c75e9e",
          "sha256": "2d08534595862fac222fdff2e894870b7bc3b07422d941f3b3bfd5bf61b3549a",
          "sha1": "5a4c15a07f9fe3af00c71919e7f52ad480191664",
          "md5": "bb9ce8105ad0f3189dd0ebfde68fd69f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.16.aar",
          "url": "acttrader-charts-android-1.3.0-beta.16.aar",
          "size": 446548,
          "sha512": "fb77dc2598e65fb3b9b1b36994803a1a40c77cc5cadf2f81254e10ff1b6a57c55a470ba667ed54a06fbffe01e98721079cf4946983edcb47ba708b18e4c75e9e",
          "sha256": "2d08534595862fac222fdff2e894870b7bc3b07422d941f3b3bfd5bf61b3549a",
          "sha1": "5a4c15a07f9fe3af00c71919e7f52ad480191664",
          "md5": "bb9ce8105ad0f3189dd0ebfde68fd69f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.16-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.16-sources.jar",
          "size": 35445,
          "sha512": "3cf7d20010ebecbed6494b4162a97073c55b4ac18952ef3856354b6dac773496f1f7f3cd9034b4f4196b327b66104b498aa95953c0bf6183df2d8867c3cd2839",
          "sha256": "7472cb7671266fa244bf6269c2ef99d764168a40bd7aedd7fad532da716c282e",
          "sha1": "bc0f1f752dd598d5d7d8f2bcdb447af6a79338b2",
          "md5": "1e8c2c6c88b34620fee6fbb6e6a43866"
        }
      ]
    }
  ]
}
