{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.3.aar",
          "url": "acttrader-charts-android-1.3.0-beta.3.aar",
          "size": 418394,
          "sha512": "be74ae920b9428508f35aee0065ed1f854ca45749f9fe52edfcc28464d9672363dc8e593573f6dca52fa2bed903824477c414e6bd66913f23571931adcb3fdc6",
          "sha256": "f54e5008e9a63dfebfdbda7a777f0c701038f47d22dcde663845fc34a671491d",
          "sha1": "e7e72aa2b5c171274bdf2ecc6eb1b5402c67b992",
          "md5": "4e5ab1416f7e8a6237e7645aad82037a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.3.aar",
          "url": "acttrader-charts-android-1.3.0-beta.3.aar",
          "size": 418394,
          "sha512": "be74ae920b9428508f35aee0065ed1f854ca45749f9fe52edfcc28464d9672363dc8e593573f6dca52fa2bed903824477c414e6bd66913f23571931adcb3fdc6",
          "sha256": "f54e5008e9a63dfebfdbda7a777f0c701038f47d22dcde663845fc34a671491d",
          "sha1": "e7e72aa2b5c171274bdf2ecc6eb1b5402c67b992",
          "md5": "4e5ab1416f7e8a6237e7645aad82037a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.3-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.3-sources.jar",
          "size": 30971,
          "sha512": "71900e8f2d607b20c00195c7f80747e27297406c23dd51f2991a356a36c837c64fb87096da6c87b984976bd590b992242852db75dc4dc96822700748eea743e2",
          "sha256": "736cbcfd98323a3dcedeb1c7e7713954d043aa98eef4cc809c158470074cfb05",
          "sha1": "1a876469f1ad36fbb2b2636c020790f121acd0bb",
          "md5": "655795cacd3eda69b3efcae34a963a1f"
        }
      ]
    }
  ]
}
