{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.30.aar",
          "url": "acttrader-charts-android-1.3.0-beta.30.aar",
          "size": 691571,
          "sha512": "c5cd7aea2e1d8bcc0c97c2cf7a4d15ce2d858687fe13d19f18a97e778dfa48f03ffddac3e26b1828beff84218e8ef6403a70d089f5db17a2be74a223825f83e2",
          "sha256": "1865eddc5112e0ee8adfa146553e436d12a41afdd2df90dadad7ca41bcb66eab",
          "sha1": "1d8470a352ce9350f4593a91221363a67705bcf2",
          "md5": "7ea49cc8093a465351cc204573a23261"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.30.aar",
          "url": "acttrader-charts-android-1.3.0-beta.30.aar",
          "size": 691571,
          "sha512": "c5cd7aea2e1d8bcc0c97c2cf7a4d15ce2d858687fe13d19f18a97e778dfa48f03ffddac3e26b1828beff84218e8ef6403a70d089f5db17a2be74a223825f83e2",
          "sha256": "1865eddc5112e0ee8adfa146553e436d12a41afdd2df90dadad7ca41bcb66eab",
          "sha1": "1d8470a352ce9350f4593a91221363a67705bcf2",
          "md5": "7ea49cc8093a465351cc204573a23261"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.30-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.30-sources.jar",
          "size": 51443,
          "sha512": "e1636ee04cf0a3374a35f84d4bc482dcbeeb0f9994adb5d0fcb1555513f0a781a71bdf4dd3eb3fa84b641cde37f60f1f6f535aa9e66a14e2e14db759c257abcf",
          "sha256": "3406993dcce9c9743212c5ed5d3ba6021f2204606a675fb98385e9ff71362e37",
          "sha1": "1cd64161614f81c43f5ed2e5fe14925d771759c1",
          "md5": "efbd7339c688fc895f3e5a2e3e782e6e"
        }
      ]
    }
  ]
}
