{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.22.aar",
          "url": "acttrader-charts-android-1.3.0-beta.22.aar",
          "size": 477335,
          "sha512": "48151d202462b380cee1504678c3af39ec49ac58f37b233f2e8c6d783cd73180dd6b9c7551ada13bb0a0acc8cf011d1383dbe09e4aaa1f926c2d9344938a4f2e",
          "sha256": "e5179d26ecb1d7801cb8c8977541d65edba767de4cfa444dd66a8de85a141008",
          "sha1": "a55298da15a8a5ead3bd45451ff246cf53526b93",
          "md5": "8bab9cf1ce8719d390d4ac5e9aff6b0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.22.aar",
          "url": "acttrader-charts-android-1.3.0-beta.22.aar",
          "size": 477335,
          "sha512": "48151d202462b380cee1504678c3af39ec49ac58f37b233f2e8c6d783cd73180dd6b9c7551ada13bb0a0acc8cf011d1383dbe09e4aaa1f926c2d9344938a4f2e",
          "sha256": "e5179d26ecb1d7801cb8c8977541d65edba767de4cfa444dd66a8de85a141008",
          "sha1": "a55298da15a8a5ead3bd45451ff246cf53526b93",
          "md5": "8bab9cf1ce8719d390d4ac5e9aff6b0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.22-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.22-sources.jar",
          "size": 38877,
          "sha512": "00f7e853d5fd31dc33150220edcdd537a23aaeb1233039cdfdc8ed63a961f13ce8725388667ac5ef048f5b8d072b672a82249006c20228ad40bb5effe39898b1",
          "sha256": "68268391a7169f64e8920af5f6de16ef1b579c38809f01b3f91ba77d2260de58",
          "sha1": "23c4d30b7a06f220a894f3638262fa203a007d26",
          "md5": "1f60537a1f6aa56a98b22bd7c949858f"
        }
      ]
    }
  ]
}
