{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.20.aar",
          "url": "acttrader-charts-android-1.3.0-beta.20.aar",
          "size": 468003,
          "sha512": "b9f759a70067f9a456208cfa0ce1104bb35362f712cd92fea98bf3729336c00df901d139cc51e1ff8adb2d80be3b97f04bef3933c9b995ffeb5db542df3689f6",
          "sha256": "1901d19b118b4d95b30698aa2a68986c3203dae98dfad98d00183c458312e7c3",
          "sha1": "fb446cdc4acc28475bf9d50448a97f788264f386",
          "md5": "5c1b38512c75f3aa7684a173a469772c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.20.aar",
          "url": "acttrader-charts-android-1.3.0-beta.20.aar",
          "size": 468003,
          "sha512": "b9f759a70067f9a456208cfa0ce1104bb35362f712cd92fea98bf3729336c00df901d139cc51e1ff8adb2d80be3b97f04bef3933c9b995ffeb5db542df3689f6",
          "sha256": "1901d19b118b4d95b30698aa2a68986c3203dae98dfad98d00183c458312e7c3",
          "sha1": "fb446cdc4acc28475bf9d50448a97f788264f386",
          "md5": "5c1b38512c75f3aa7684a173a469772c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.20-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.20-sources.jar",
          "size": 37821,
          "sha512": "1e56405765767dd840a68e5441a7aeaed182db4bada1f3a12fe6ceb567088ceca42eb8d10be57b1d16866ab37164363d2a6dff044e0ce0f52f412ab3f645e03c",
          "sha256": "37f6507f6610c3b3ad7d45fff315d9babd37b3e302849833a3572cca97c6fe06",
          "sha1": "41a8a2f993e9dcbb0620c736a9cafacb90add216",
          "md5": "b4eb495befb215da73e2e4121537e3df"
        }
      ]
    }
  ]
}
