{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.10.aar",
          "url": "acttrader-charts-android-1.3.0-beta.10.aar",
          "size": 431379,
          "sha512": "c617cccce368b2313de915b950b5fd0f35a7e7254197c7d1bc40b077b63cb8b2e09e1fe80bffe452024fceea0c87d2fa24b0623b62d3c97563138d326c828634",
          "sha256": "a6959db7592b4b827e9ff01487270e674f407971c7a7e63ebe8d92fa634b1f37",
          "sha1": "2810ef28688386945235af610306148cf831a9e7",
          "md5": "6bbe0af8430b152300ee12dfe540bf2d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.10.aar",
          "url": "acttrader-charts-android-1.3.0-beta.10.aar",
          "size": 431379,
          "sha512": "c617cccce368b2313de915b950b5fd0f35a7e7254197c7d1bc40b077b63cb8b2e09e1fe80bffe452024fceea0c87d2fa24b0623b62d3c97563138d326c828634",
          "sha256": "a6959db7592b4b827e9ff01487270e674f407971c7a7e63ebe8d92fa634b1f37",
          "sha1": "2810ef28688386945235af610306148cf831a9e7",
          "md5": "6bbe0af8430b152300ee12dfe540bf2d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.10-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.10-sources.jar",
          "size": 32570,
          "sha512": "4b34fca7dc24a498b1021429bf59b9f04b0b368f5dd0ce24cc2c13f501de866f2577e835ce601b92c6aaec11c0c3e10cb4aa4fed2df191f6800d69f9ef315ce3",
          "sha256": "d087be437e3a0f60cbfda2553649856f0bc65ff03f916b1223d93e1d5665de97",
          "sha1": "583292099484b08dfee65bfde9ffaf6ea72a55bc",
          "md5": "e95abc1d8fb305b3856f896dd060faee"
        }
      ]
    }
  ]
}
