{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.23.aar",
          "url": "acttrader-charts-android-1.3.0-beta.23.aar",
          "size": 477422,
          "sha512": "1c3fcdc98a7664db7fc874e3411c46bc52417279efeeca444407a8df638cb3b59370846ddb0098719e4456662163b799ffe4d1e5f134d9b152c6ae0afa9f92d4",
          "sha256": "217a6d3ea1e39891237dad3d846455c91a9c16930900270af9a72730b9b23f5c",
          "sha1": "7e8a715ac3f039495732c10c7ac86fc4f97006fb",
          "md5": "117de0d5ec53fe6d17528ece3a7099d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.23.aar",
          "url": "acttrader-charts-android-1.3.0-beta.23.aar",
          "size": 477422,
          "sha512": "1c3fcdc98a7664db7fc874e3411c46bc52417279efeeca444407a8df638cb3b59370846ddb0098719e4456662163b799ffe4d1e5f134d9b152c6ae0afa9f92d4",
          "sha256": "217a6d3ea1e39891237dad3d846455c91a9c16930900270af9a72730b9b23f5c",
          "sha1": "7e8a715ac3f039495732c10c7ac86fc4f97006fb",
          "md5": "117de0d5ec53fe6d17528ece3a7099d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.23-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.23-sources.jar",
          "size": 38877,
          "sha512": "00f7e853d5fd31dc33150220edcdd537a23aaeb1233039cdfdc8ed63a961f13ce8725388667ac5ef048f5b8d072b672a82249006c20228ad40bb5effe39898b1",
          "sha256": "68268391a7169f64e8920af5f6de16ef1b579c38809f01b3f91ba77d2260de58",
          "sha1": "23c4d30b7a06f220a894f3638262fa203a007d26",
          "md5": "1f60537a1f6aa56a98b22bd7c949858f"
        }
      ]
    }
  ]
}
