{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.26.aar",
          "url": "acttrader-charts-android-1.3.0-beta.26.aar",
          "size": 488173,
          "sha512": "8f700b5cc5e62de7f41c410607f86869770a76ba256d391093eecb6575e47f44520ebc05e98a80e8dd33f7097a5b3c4abdf3b5ab781824c6d485cec37693216f",
          "sha256": "ee3e3dcd3ae9e06a9e54916c36a5c6b6ea905e5de028e420206e65619ae27c81",
          "sha1": "4d4008bb197a5395cf76bd7625e19716f96648ac",
          "md5": "8424656963158c8efdd4ca82fa2ffc99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.26.aar",
          "url": "acttrader-charts-android-1.3.0-beta.26.aar",
          "size": 488173,
          "sha512": "8f700b5cc5e62de7f41c410607f86869770a76ba256d391093eecb6575e47f44520ebc05e98a80e8dd33f7097a5b3c4abdf3b5ab781824c6d485cec37693216f",
          "sha256": "ee3e3dcd3ae9e06a9e54916c36a5c6b6ea905e5de028e420206e65619ae27c81",
          "sha1": "4d4008bb197a5395cf76bd7625e19716f96648ac",
          "md5": "8424656963158c8efdd4ca82fa2ffc99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.26-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.26-sources.jar",
          "size": 39590,
          "sha512": "09a06a2b2628b89cd6ecf26c29eec2dd6caa610c5d136a8dba75864a518134e6cc7e870d852ec8842dddbb64657e638fc886e4499445d21fbeef196dbc3d2100",
          "sha256": "fded3c93ba3dba2914e7162e8e75113ea02ec2a31764b1cff7d434009dc6b5e6",
          "sha1": "ef4a084c38a9c6084e7e55864053eab93083d807",
          "md5": "3e594f1f5573bf4f02a847d652955340"
        }
      ]
    }
  ]
}
