{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.12.aar",
          "url": "acttrader-charts-android-1.3.0-beta.12.aar",
          "size": 445688,
          "sha512": "ec838906312c0df730dda1a94671903e1579d293f72c30dc4a3534918ca1646c9c9c5442fa6630788a4b47b0f0c5397e5883f9b0dd471bc30da2065e91c3a37a",
          "sha256": "ff791d16a54dc5912ac4069fc392494dba6c8ad91648b6f092aa9b92f245ddbd",
          "sha1": "e8a37fa4b419ab253c595604f92426e700cfdb60",
          "md5": "7e49fb080af93c9f4ce883e2f227ab95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.12.aar",
          "url": "acttrader-charts-android-1.3.0-beta.12.aar",
          "size": 445688,
          "sha512": "ec838906312c0df730dda1a94671903e1579d293f72c30dc4a3534918ca1646c9c9c5442fa6630788a4b47b0f0c5397e5883f9b0dd471bc30da2065e91c3a37a",
          "sha256": "ff791d16a54dc5912ac4069fc392494dba6c8ad91648b6f092aa9b92f245ddbd",
          "sha1": "e8a37fa4b419ab253c595604f92426e700cfdb60",
          "md5": "7e49fb080af93c9f4ce883e2f227ab95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.12-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.12-sources.jar",
          "size": 35445,
          "sha512": "3cf7d20010ebecbed6494b4162a97073c55b4ac18952ef3856354b6dac773496f1f7f3cd9034b4f4196b327b66104b498aa95953c0bf6183df2d8867c3cd2839",
          "sha256": "7472cb7671266fa244bf6269c2ef99d764168a40bd7aedd7fad532da716c282e",
          "sha1": "bc0f1f752dd598d5d7d8f2bcdb447af6a79338b2",
          "md5": "1e8c2c6c88b34620fee6fbb6e6a43866"
        }
      ]
    }
  ]
}
