{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.6.aar",
          "url": "acttrader-charts-android-1.3.0-beta.6.aar",
          "size": 419382,
          "sha512": "c5fcdb37b197c9ff0a5e8c7dd0ff2a33ebe0ce71aca2306e77065d998f5465d976a772f05b5528625c30286b4eae1e01a9b83727579532dcf22b97132573e52e",
          "sha256": "325886bae3aa031b429ab6f9408d3526a27ebcc1fd03f16b09042a05371e1fbe",
          "sha1": "1feb1ce009fdd8d2f04374617feb9bdf950e1162",
          "md5": "983836856f71700c4cb91fcc8214be2c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.6.aar",
          "url": "acttrader-charts-android-1.3.0-beta.6.aar",
          "size": 419382,
          "sha512": "c5fcdb37b197c9ff0a5e8c7dd0ff2a33ebe0ce71aca2306e77065d998f5465d976a772f05b5528625c30286b4eae1e01a9b83727579532dcf22b97132573e52e",
          "sha256": "325886bae3aa031b429ab6f9408d3526a27ebcc1fd03f16b09042a05371e1fbe",
          "sha1": "1feb1ce009fdd8d2f04374617feb9bdf950e1162",
          "md5": "983836856f71700c4cb91fcc8214be2c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.6-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.6-sources.jar",
          "size": 30971,
          "sha512": "71900e8f2d607b20c00195c7f80747e27297406c23dd51f2991a356a36c837c64fb87096da6c87b984976bd590b992242852db75dc4dc96822700748eea743e2",
          "sha256": "736cbcfd98323a3dcedeb1c7e7713954d043aa98eef4cc809c158470074cfb05",
          "sha1": "1a876469f1ad36fbb2b2636c020790f121acd0bb",
          "md5": "655795cacd3eda69b3efcae34a963a1f"
        }
      ]
    }
  ]
}
