{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.9.aar",
          "url": "acttrader-charts-android-1.3.0-beta.9.aar",
          "size": 426710,
          "sha512": "06e2a53cf341840427cc7658ed26369defad9ffdd7ad39cb500931958fbfd837bac5b027f9bb2cbef5cfa67e893c7515857c819ce5b1c22e1f08f9e689d3cb8c",
          "sha256": "5aba2fe5c914dac79c0fe48109f19cb6c6c091a4ff835b8701a007977a28f4ae",
          "sha1": "6abb82317b7e60e0c12eba23640b2b0a45823256",
          "md5": "cdeeb5aa166057e90e8993d9fedc7d48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.9.aar",
          "url": "acttrader-charts-android-1.3.0-beta.9.aar",
          "size": 426710,
          "sha512": "06e2a53cf341840427cc7658ed26369defad9ffdd7ad39cb500931958fbfd837bac5b027f9bb2cbef5cfa67e893c7515857c819ce5b1c22e1f08f9e689d3cb8c",
          "sha256": "5aba2fe5c914dac79c0fe48109f19cb6c6c091a4ff835b8701a007977a28f4ae",
          "sha1": "6abb82317b7e60e0c12eba23640b2b0a45823256",
          "md5": "cdeeb5aa166057e90e8993d9fedc7d48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.9-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.9-sources.jar",
          "size": 31949,
          "sha512": "32dd82807ff10567fcd644e070fc00fef4f3ed7048bb5060a724d13da5516e3f7eb988511e744dd30a62a08e8581a679da3f204cfb7ff900e28fcc8b72141c40",
          "sha256": "a295a0dc59c512f7672826e2d42d6e7906c7fa2f0b4945df918d00087b5bd2f2",
          "sha1": "fe02a2337ea8f19cef519e4f2fdfc5cddd59a90a",
          "md5": "05724406efc755e7d689111639ee9a82"
        }
      ]
    }
  ]
}
