{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.21.aar",
          "url": "acttrader-charts-android-1.3.0-beta.21.aar",
          "size": 477336,
          "sha512": "aa7bed861d2c33444200be5da6433cf9146c181f8356b35a569a4ab1253f5b6e5c238f5ea733815dcdf838660b5b3855ed0ca7954032ebbb3bfd0a5aded597e5",
          "sha256": "8dc68891cd1ebbb4d2909719d06bc930e3d608dd5cacf0715d833a0d9942e37b",
          "sha1": "364a8f15ed7bb089ca6dec91fc8e1352f7021a48",
          "md5": "01da71a49f1b4d4cbcaf38589c1da8a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.21.aar",
          "url": "acttrader-charts-android-1.3.0-beta.21.aar",
          "size": 477336,
          "sha512": "aa7bed861d2c33444200be5da6433cf9146c181f8356b35a569a4ab1253f5b6e5c238f5ea733815dcdf838660b5b3855ed0ca7954032ebbb3bfd0a5aded597e5",
          "sha256": "8dc68891cd1ebbb4d2909719d06bc930e3d608dd5cacf0715d833a0d9942e37b",
          "sha1": "364a8f15ed7bb089ca6dec91fc8e1352f7021a48",
          "md5": "01da71a49f1b4d4cbcaf38589c1da8a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.21-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.21-sources.jar",
          "size": 38877,
          "sha512": "00f7e853d5fd31dc33150220edcdd537a23aaeb1233039cdfdc8ed63a961f13ce8725388667ac5ef048f5b8d072b672a82249006c20228ad40bb5effe39898b1",
          "sha256": "68268391a7169f64e8920af5f6de16ef1b579c38809f01b3f91ba77d2260de58",
          "sha1": "23c4d30b7a06f220a894f3638262fa203a007d26",
          "md5": "1f60537a1f6aa56a98b22bd7c949858f"
        }
      ]
    }
  ]
}
