{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.24.aar",
          "url": "acttrader-charts-android-1.3.0-beta.24.aar",
          "size": 477401,
          "sha512": "488c090f6b48c0119b06274be1230a7e9878053c16ca86310bc77e267bde7ec75aa8087bc1fda77f4a901101163d595935066ba4b0ef5b5373edafe9784117c9",
          "sha256": "ba60a85ad72f6ba192d7cefc9cfb7f9b2e201c57d6d3b1d1295f473c039fa9f0",
          "sha1": "e9aa71816214b36c62d1def3570ab82b5bcd7ca7",
          "md5": "a810859db94c5a54fbf3a87c3ab6bf9f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.24.aar",
          "url": "acttrader-charts-android-1.3.0-beta.24.aar",
          "size": 477401,
          "sha512": "488c090f6b48c0119b06274be1230a7e9878053c16ca86310bc77e267bde7ec75aa8087bc1fda77f4a901101163d595935066ba4b0ef5b5373edafe9784117c9",
          "sha256": "ba60a85ad72f6ba192d7cefc9cfb7f9b2e201c57d6d3b1d1295f473c039fa9f0",
          "sha1": "e9aa71816214b36c62d1def3570ab82b5bcd7ca7",
          "md5": "a810859db94c5a54fbf3a87c3ab6bf9f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.24-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.24-sources.jar",
          "size": 38877,
          "sha512": "00f7e853d5fd31dc33150220edcdd537a23aaeb1233039cdfdc8ed63a961f13ce8725388667ac5ef048f5b8d072b672a82249006c20228ad40bb5effe39898b1",
          "sha256": "68268391a7169f64e8920af5f6de16ef1b579c38809f01b3f91ba77d2260de58",
          "sha1": "23c4d30b7a06f220a894f3638262fa203a007d26",
          "md5": "1f60537a1f6aa56a98b22bd7c949858f"
        }
      ]
    }
  ]
}
