{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acttrader",
    "module": "acttrader-charts-android",
    "version": "1.3.0-beta.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.19.aar",
          "url": "acttrader-charts-android-1.3.0-beta.19.aar",
          "size": 455902,
          "sha512": "a05a7358492ca23e08cef4a88a2ab5bd4b2bdbec553a40d2fc861a075acee7676fc6f78b1302dfb5bccd9f63df771841c541553c6d1c8393588289d6a5b9b14c",
          "sha256": "09e165cb5ecb9ea62679d934f544e48adf068287a062ba6423bf425dd39322dc",
          "sha1": "3a1b0e194a914d0eafe75bd5bb45147671ea34ae",
          "md5": "379fab424f99b721a89df6f247d70f86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.06.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.19.aar",
          "url": "acttrader-charts-android-1.3.0-beta.19.aar",
          "size": 455902,
          "sha512": "a05a7358492ca23e08cef4a88a2ab5bd4b2bdbec553a40d2fc861a075acee7676fc6f78b1302dfb5bccd9f63df771841c541553c6d1c8393588289d6a5b9b14c",
          "sha256": "09e165cb5ecb9ea62679d934f544e48adf068287a062ba6423bf425dd39322dc",
          "sha1": "3a1b0e194a914d0eafe75bd5bb45147671ea34ae",
          "md5": "379fab424f99b721a89df6f247d70f86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acttrader-charts-android-1.3.0-beta.19-sources.jar",
          "url": "acttrader-charts-android-1.3.0-beta.19-sources.jar",
          "size": 35445,
          "sha512": "3cf7d20010ebecbed6494b4162a97073c55b4ac18952ef3856354b6dac773496f1f7f3cd9034b4f4196b327b66104b498aa95953c0bf6183df2d8867c3cd2839",
          "sha256": "7472cb7671266fa244bf6269c2ef99d764168a40bd7aedd7fad532da716c282e",
          "sha1": "bc0f1f752dd598d5d7d8f2bcdb447af6a79338b2",
          "md5": "1e8c2c6c88b34620fee6fbb6e6a43866"
        }
      ]
    }
  ]
}
